# Source of truth for UI strings: generates src/i18n/en.json and zh-Hant.json
# with identical key sets. Run: python scripts/strings.py
import json
import pathlib

S = {
    "app.title": ("German Word Families", "德文詞族"),
    "app.tagline": ("See how German words grow from one another.", "看德文單字如何一個接一個長出來。"),
    "search.placeholder": ("Type any German word or form", "輸入任何德文單字或變化形"),
    "search.label": ("Search a German word", "搜尋德文單字"),
    "search.submit": ("Search", "搜尋"),
    "search.insert": ("Insert {c}", "插入 {c}"),
    "search.specialChars": ("Special letters ä ö ü ß", "特殊字母 ä ö ü ß"),
    "search.didYouMean": ("Did you mean {word}?", "您是不是要找 {word}？"),
    "search.notFound": ("No match for \"{q}\". Try the dictionary form.", "找不到「{q}」。試試原形。"),
    "search.scriptHint": ("Type in German using Latin letters.", "請用拉丁字母輸入德文。"),
    "search.chooseLemma": ("This form belongs to several words. Choose one:", "這個形式屬於幾個不同的詞，請選擇："),
    "search.searching": ("Searching…", "搜尋中…"),
    "nav.family": ("Family", "詞族"),
    "nav.browse": ("Browse", "瀏覽"),
    "nav.guide": ("How it works", "使用說明"),
    "nav.main": ("Main", "主選單"),
    "lang.toggle": ("Switch language", "切換語言"),
    "home.stepsTitle": ("How to use", "使用方式"),
    "home.step1": ("Type a German word, in any form.", "輸入一個德文單字，任何變化形都可以。"),
    "home.step2": ("Explore its family: how each word grows from another.", "探索它的詞族：看每個詞如何由另一個詞衍生而來。"),
    "home.step3": ("Filter by level, part of speech or word formation.", "依等級、詞性或構詞方式篩選。"),
    "home.learnMore": ("How does this work?", "這是怎麼運作的？"),
    "home.examples": ("Try a family", "試試這些詞族"),
    "home.stats": ("{families} families · {words} words · {compounds} compounds", "{families} 個詞族 · {words} 個詞 · {compounds} 個複合詞"),
    "help.open": ("What do these colors mean?", "這些顏色代表什麼？"),
    "help.title": ("How to read the tree", "如何閱讀樹狀圖"),
    "help.more": ("Read the full guide", "閱讀完整說明"),
    "legend.articles": ("Articles (noun gender)", "冠詞（名詞性別）"),
    "legend.morphemes": ("Word parts", "詞的組成部分"),
    "legend.bar": ("Separable prefix: it splits off in main clauses", "可分前綴：主句中會分離"),
    "legend.dot": ("Joins the parts of a compound", "連接複合詞的各部分"),
    "legend.dashed": ("Dashed border: estimated level", "虛線外框：估計的等級"),
    "legend.uncertain": ("Dashed underline: the split is a guess", "虛線底線：切分為推測"),
    "legend.faded": ("Faded: rare word, shown to connect the tree", "淡色：罕用詞，為了連接樹而顯示"),
    "legend.next": ("Bold outline: one level above yours", "粗外框：比你的程度高一級"),
    "legend.levels": ("Levels", "等級"),
    "legend.pos": ("Parts of speech", "詞性"),
    "legend.marks": ("Marks", "標記"),
    "view.tree": ("Tree", "樹狀圖"),
    "view.outline": ("Outline", "大綱"),
    "view.label": ("View", "檢視"),
    "filter.title": ("Filters", "篩選"),
    "filter.open": ("Show filters", "顯示篩選"),
    "filter.close": ("Hide filters", "隱藏篩選"),
    "filter.done": ("Done", "完成"),
    "filter.clear": ("Clear filters", "清除篩選"),
    "filter.remove": ("Remove filter {name}", "移除篩選 {name}"),
    "filter.mode": ("Show non-matching words", "不符合的詞"),
    "filter.mode.dim": ("Dimmed", "淡化顯示"),
    "filter.mode.prune": ("Hidden", "隱藏"),
    "filter.mode.list": ("As a list", "改為清單"),
    "filter.level": ("CEFR level", "CEFR 等級"),
    "filter.pos": ("Part of speech", "詞性"),
    "filter.gender": ("Gender", "性別"),
    "filter.plural": ("Plural pattern", "複數類型"),
    "filter.conjugation": ("Conjugation", "變位類型"),
    "filter.prefixType": ("Prefix type", "前綴類型"),
    "filter.auxiliary": ("Auxiliary in perfect tense", "完成式助動詞"),
    "filter.reflexive": ("Reflexive verbs only", "只顯示反身動詞"),
    "filter.formation": ("Formation type", "構詞類型"),
    "filter.posChange": ("Part-of-speech change", "詞性轉換"),
    "filter.vowelChange": ("Vowel change", "母音變化"),
    "filter.affix": ("Contains affix", "含有詞綴"),
    "filter.affixPlaceholder": ("Type an affix, e.g. ver- or -ung", "輸入詞綴，例如 ver- 或 -ung"),
    "filter.topic": ("Topic", "主題"),
    "filter.freq": ("Frequency", "常用程度"),
    "filter.freqAny": ("Any", "不限"),
    "filter.freqMin": ("{n}+ stars", "{n} 星以上"),
    "filter.hideUncertain": ("Hide uncertain splits", "隱藏不確定的切分"),
    "filter.minMatches": ("At least {n} matching words", "至少 {n} 個符合的詞"),
    "filter.matches": ("{n} of {total} words match", "{total} 個詞中有 {n} 個符合"),
    "filter.nounGroup": ("Nouns", "名詞"),
    "filter.verbGroup": ("Verbs", "動詞"),
    "filter.formationGroup": ("Word formation", "構詞"),
    "filter.otherGroup": ("More", "更多"),
    "settings.title": ("Settings", "設定"),
    "settings.open": ("Open settings", "開啟設定"),
    "settings.levelSource": ("Level source", "分級依據"),
    "settings.levelSource.estimated": ("Estimated from frequency", "依詞頻估計"),
    "settings.levelSource.custom": ("Custom list", "自訂詞表"),
    "settings.myLevel": ("My level", "我的程度"),
    "settings.myLevel.none": ("None", "未設定"),
    "settings.colorBy": ("Color nodes by", "節點著色依據"),
    "settings.colorBy.level": ("Level", "等級"),
    "settings.colorBy.pos": ("Part of speech", "詞性"),
    "settings.colorBy.gender": ("Noun gender", "名詞性別"),
    "settings.theme": ("Theme", "主題"),
    "settings.theme.system": ("System", "跟隨系統"),
    "settings.theme.light": ("Light", "淺色"),
    "settings.theme.dark": ("Dark", "深色"),
    "tree.showMore": ("Show {n} more", "再顯示 {n} 個"),
    "tree.pathNode": ("Rare word, shown to connect the tree", "罕用詞，為了連接樹而顯示"),
    "tree.umlaut": ("Umlaut", "變音"),
    "tree.ablaut": ("Vowel change (ablaut)", "母音交替"),
    "tree.label": ("Word family of {word}", "{word} 的詞族"),
    "tree.zoomIn": ("Zoom in", "放大"),
    "tree.zoomOut": ("Zoom out", "縮小"),
    "tree.reset": ("Fit to screen", "符合畫面"),
    "tree.expand": ("Expand", "展開"),
    "tree.collapse": ("Collapse", "收合"),
    "tree.keyboardHint": ("Arrow keys move, Enter opens details, Space expands or collapses.", "方向鍵移動、Enter 開啟詳細資訊、空白鍵展開或收合。"),
    "tree.conversion": ("No affix", "無詞綴"),
    "compounds.title": ("Compounds", "複合詞"),
    "compounds.asModifier": ("As first part", "作為前項"),
    "compounds.asHead": ("As last part (head)", "作為中心詞（後項）"),
    "compounds.genderHint": ("A compound takes the gender of its last part.", "複合詞的性別跟隨最後一個部件。"),
    "compounds.link": ("Linking element", "連接成分"),
    "compounds.showAll": ("Show all", "顯示全部"),
    "compounds.showLess": ("Show fewer", "顯示較少"),
    "compounds.none": ("No compounds found.", "沒有找到複合詞。"),
    "compounds.partsOf": ("This word is a compound of:", "這個詞由以下部件組成："),
    "compounds.count": ("{n} compounds", "{n} 個複合詞"),
    "detail.title": ("Word details", "單字詳細資訊"),
    "detail.close": ("Close details", "關閉詳細資訊"),
    "detail.empty": ("Select a word in the tree to see its details.", "在樹狀圖中選擇一個詞以查看詳細資訊。"),
    "detail.addedFrom": ("Formed from {parent} by adding", "由 {parent} 加上"),
    "detail.conversion": ("Formed from {parent} without an affix", "由 {parent} 直接轉換而來"),
    "detail.uncertainLink": ("Related to {parent}; the exact formation is unclear.", "與 {parent} 相關，確切的構詞方式不明。"),
    "detail.umlautNote": ("The stem vowel takes an umlaut.", "詞幹母音變為變音。"),
    "detail.ablautNote": ("The stem vowel changes (ablaut).", "詞幹母音發生交替（Ablaut）。"),
    "detail.principalParts": ("Principal parts", "主要形式"),
    "detail.genitive": ("Genitive", "屬格"),
    "detail.plural": ("Plural", "複數"),
    "detail.pluralType": ("Plural pattern", "複數類型"),
    "detail.comparative": ("Comparative", "比較級"),
    "detail.superlative": ("Superlative", "最高級"),
    "detail.separable": ("Separable: the prefix splits off in main clauses", "可分動詞：主句中前綴會分離"),
    "detail.inseparable": ("Inseparable: the prefix never splits off", "不可分動詞：前綴永不分離"),
    "detail.twoMeanings": ("Same spelling, two verbs", "同形的兩個動詞"),
    "detail.examples": ("Examples", "例句"),
    "detail.uncertain": ("This split is a guess and may be wrong.", "此切分為推測，可能有誤。"),
    "detail.estimated": ("Level estimated from word frequency", "等級依詞頻估計"),
    "detail.customLevel": ("Level from your custom list", "等級來自你的自訂詞表"),
    "detail.noGloss": ("No definition available", "暫無釋義"),
    "detail.meaning": ("Meaning", "釋義"),
    "detail.formation": ("Formation", "構詞"),
    "detail.parts": ("Compound parts", "複合詞部件"),
    "detail.topics": ("Topics", "主題"),
    "detail.frequency": ("Frequency", "常用程度"),
    "detail.stars": ("{n} of 5", "5 顆星中的 {n} 顆"),
    "detail.level": ("Level", "等級"),
    "detail.grammar": ("Grammar", "文法"),
    "detail.conjugation": ("Conjugation", "變位類型"),
    "detail.reflexive": ("Reflexive (sich)", "反身動詞（sich）"),
    "detail.openFamily": ("Open its family", "開啟它的詞族"),
    "detail.enBadge": ("EN", "EN"),
    "detail.enBadgeTitle": ("No Chinese definition yet; showing English", "尚無中文釋義，顯示英文"),
    "detail.pathNode": ("This word is rare. It is shown so the tree stays connected.", "這個詞很少用，顯示它是為了讓樹保持連接。"),
    "detail.root": ("This is the root of the family.", "這是詞族的樹根。"),
    "detail.ipa": ("Pronunciation", "發音"),
    "dict.title": ("Dictionaries", "外部字典"),
    "dict.newTab": ("opens in a new tab", "在新分頁開啟"),
    "dict.hint.wiktionary": ("definitions and full inflection tables", "釋義與完整變化表"),
    "dict.hint.dewiktionary": ("German definitions, grammar and examples", "德文釋義、文法與例句"),
    "dict.hint.dwds": ("German dictionary with corpus examples", "德文辭典與語料例句"),
    "dict.hint.duden": ("spelling and meanings (German)", "拼字與釋義（德文）"),
    "dict.hint.leo": ("translations and forum", "翻譯與論壇"),
    "dict.hint.linguee": ("translations in real sentences", "真實句子中的翻譯"),
    "dict.hint.forvo": ("pronunciation by native speakers", "母語者發音"),
    "morph.PREF_SEP": ("Separable prefix", "可分前綴"),
    "morph.PREF": ("Prefix", "前綴"),
    "morph.ROOT": ("Stem", "詞幹"),
    "morph.SUFF": ("Suffix", "後綴"),
    "morph.END": ("Ending", "詞尾"),
    "morph.LINK": ("Linking element", "連接成分"),
    "level.beyond": ("Beyond C2", "超出分級"),
    "level.next": ("Next", "下一步"),
    "pos.NOUN": ("Noun", "名詞"),
    "pos.VERB": ("Verb", "動詞"),
    "pos.ADJ": ("Adjective", "形容詞"),
    "pos.ADV": ("Adverb", "副詞"),
    "pos.OTHER": ("Other", "其他"),
    "gender.masc": ("der (masculine)", "der（陽性）"),
    "gender.femn": ("die (feminine)", "die（陰性）"),
    "gender.neut": ("das (neuter)", "das（中性）"),
    "gender.multiple": ("Multiple", "多種性別"),
    "gender.plural_only": ("Plural only", "只有複數"),
    "gender.unknown": ("Other", "其他"),
    "plural.e": ("-e", "加 -e"),
    "plural.uml_e": ("¨-e", "變音加 -e"),
    "plural.er": ("-er", "加 -er"),
    "plural.uml_er": ("¨-er", "變音加 -er"),
    "plural.en": ("-(e)n", "加 -(e)n"),
    "plural.s": ("-s", "加 -s"),
    "plural.zero": ("no ending", "不變"),
    "plural.uml_zero": ("¨ only", "只變音"),
    "plural.other": ("Other", "其他"),
    "plural.none": ("No plural", "無複數"),
    "conj.weak": ("Weak", "弱變化"),
    "conj.strong": ("Strong", "強變化"),
    "conj.mixed": ("Mixed", "混合變化"),
    "conj.irregular": ("Irregular", "不規則"),
    "conj.modal": ("Modal", "情態動詞"),
    "conj.unknown": ("Other", "其他"),
    "pt.separable": ("Separable", "可分動詞"),
    "pt.inseparable": ("Inseparable", "不可分動詞"),
    "pt.none": ("No prefix", "無前綴"),
    "pt.unknown": ("Other", "其他"),
    "aux.haben": ("haben", "haben"),
    "aux.sein": ("sein", "sein"),
    "aux.both": ("Both", "兩者皆可"),
    "aux.unknown": ("Other", "其他"),
    "vc.umlaut": ("Umlaut", "變音"),
    "vc.ablaut": ("Ablaut", "母音交替"),
    "sem.action_noun": ("Action noun", "動作名詞"),
    "sem.agent_noun": ("Agent noun", "施事者名詞"),
    "sem.person_noun": ("Person noun", "人物名詞"),
    "sem.feminine": ("Feminine counterpart", "陰性對應詞"),
    "sem.quality_noun": ("Quality noun", "性質名詞"),
    "sem.collective_noun": ("Collective noun", "集合名詞"),
    "sem.result_noun": ("Result noun", "結果名詞"),
    "sem.place_noun": ("Place / activity noun", "場所／活動名詞"),
    "sem.diminutive": ("Diminutive", "指小詞"),
    "sem.relational_adj": ("Relational adjective", "關係形容詞"),
    "sem.ability_adj": ("\"-able\" adjective", "可能性形容詞"),
    "sem.privative_adj": ("\"-less\" adjective", "缺乏義形容詞"),
    "sem.material_adj": ("Material adjective", "材料形容詞"),
    "sem.verbalizer": ("Verb-forming", "轉動詞"),
    "sem.diminutive_verb": ("Diminutive verb", "輕化動詞"),
    "sem.nominalized_infinitive": ("Nominalized infinitive", "不定式名詞化"),
    "sem.stem_noun": ("Stem noun", "詞幹名詞"),
    "sem.nominalized_adjective": ("Nominalized adjective", "形容詞名詞化"),
    "sem.denominal_verb": ("Verb from noun", "名詞轉動詞"),
    "sem.deadjectival_verb": ("Verb from adjective", "形容詞轉動詞"),
    "sem.prefixed_verb": ("Prefixed verb", "前綴動詞"),
    "sem.other": ("Other", "其他"),
    "affixKind.separable": ("Separable prefixes", "可分前綴"),
    "affixKind.inseparable": ("Inseparable prefixes", "不可分前綴"),
    "affixKind.dual": ("Separable or inseparable", "可分或不可分"),
    "affixKind.nominal": ("Noun and adjective prefixes", "名詞與形容詞前綴"),
    "affixKind.suffix": ("Suffixes", "後綴"),
    "browse.title": ("Browse", "瀏覽"),
    "browse.tab.families": ("Families", "詞族"),
    "browse.tab.affixes": ("Affixes", "詞綴"),
    "browse.tab.formation": ("Formation patterns", "構詞規律"),
    "browse.tab.compounds": ("Compounds", "複合詞"),
    "browse.empty": ("Nothing matches these filters. Remove a filter to see more.", "沒有符合條件的結果。移除一個篩選條件試試。"),
    "browse.sort": ("Sort by", "排序依據"),
    "browse.sort.level": ("Lowest level", "最低等級"),
    "browse.sort.size": ("Family size", "詞族大小"),
    "browse.sort.alpha": ("Alphabetical", "字母順序"),
    "browse.col.root": ("Root word", "樹根詞"),
    "browse.col.meaning": ("Meaning", "釋義"),
    "browse.col.minLevel": ("Lowest level", "最低等級"),
    "browse.col.size": ("Words", "詞數"),
    "browse.col.levels": ("Levels", "等級分布"),
    "browse.col.compounds": ("Compounds", "複合詞"),
    "browse.col.parent": ("From", "來源詞"),
    "browse.col.child": ("New word", "新詞"),
    "browse.col.word": ("Word", "單字"),
    "browse.results": ("{n} results", "{n} 筆結果"),
    "browse.page": ("Page {n} of {m}", "第 {n} 頁，共 {m} 頁"),
    "browse.prev": ("Previous", "上一頁"),
    "browse.next": ("Next", "下一頁"),
    "browse.chooseAffix": ("Choose an affix", "選擇一個詞綴"),
    "browse.affixWords": ("Words with {affix}", "含有 {affix} 的詞"),
    "browse.dualCompare": ("Same prefix, two behaviours", "同一個前綴，兩種用法"),
    "browse.dualSep": ("Separable (stressed prefix)", "可分（重音在前綴）"),
    "browse.dualInsep": ("Inseparable (stressed stem)", "不可分（重音在詞幹）"),
    "browse.chooseFormation": ("Choose a formation type or part-of-speech change", "選擇構詞類型或詞性轉換"),
    "browse.vowelView": ("Vowel change", "母音變化"),
    "browse.bySemantic": ("By formation type", "依構詞類型"),
    "browse.byPosChange": ("By part-of-speech change", "依詞性轉換"),
    "browse.choosePart": ("Type a word to see compounds built with it", "輸入一個詞，查看用它組成的複合詞"),
    "browse.byLink": ("By linking element", "依連接成分"),
    "browse.linkNone": ("None", "無"),
    "browse.linkHint": ("Linking elements join the parts of a compound: Arbeit·s·platz, Straße·n·bahn.", "連接成分把複合詞的部件接起來：Arbeit·s·platz、Straße·n·bahn。"),
    "browse.loading": ("Loading word list…", "正在載入單字清單…"),
    "common.loading": ("Loading…", "載入中…"),
    "common.error": ("Could not load the data. Please reload the page.", "無法載入資料，請重新整理頁面。"),
    "common.close": ("Close", "關閉"),
    "common.all": ("All", "全部"),
    "common.skip": ("Skip to content", "跳到主要內容"),
    "family.notFound": ("This family does not exist.", "找不到這個詞族。"),
    "family.back": ("Back to search", "回到搜尋"),
    "family.words": ("{n} words", "{n} 個詞"),
    "list.sort": ("Sort list by", "清單排序依據"),
    "list.byLevel": ("Level", "等級"),
    "list.byStars": ("Frequency", "常用程度"),
    "notFound.title": ("Page not found", "找不到頁面"),
    "footer.data": ("Data: DErivBase, Wiktionary, CharSplit, wordfreq (CC BY-SA 4.0). Code: MIT.", "資料：DErivBase、Wiktionary、CharSplit、wordfreq（CC BY-SA 4.0）。程式碼：MIT。"),
    "footer.report": ("Report a problem", "回報問題"),
    "guide.title": ("How it works", "使用說明"),
    "guide.s1.title": ("What this tool does", "這個工具做什麼"),
    "guide.s1.body": ("German builds many words from a small set of stems. This tool shows how words are related: which word each one comes from, what was added, and what it means. Seeing the pattern once helps you understand many new words.", "德文用少量詞幹組出大量單字。這個工具把詞與詞之間的關係畫出來：每個詞從哪個詞而來、加了什麼、意思怎麼變。看懂一次規律，就能讀懂許多新詞。"),
    "guide.s2.title": ("How to read a family", "如何閱讀詞族"),
    "guide.s2.body": ("Each box is a word; each line means \"formed from\". The label on a line shows what was added, such as a prefix or suffix. A vertical bar (auf|stehen) marks a separable prefix. A middle dot (Haus·tür) joins the parts of a compound. Below the tree, you'll find compounds that contain words from this family.", "每個方框是一個詞，每條線代表「由……衍生」。線上的標籤說明加了什麼，例如前綴或後綴。直線（auf|stehen）表示可分前綴，中間點（Haus·tür）連接複合詞的各部分。樹的下方列出含有這個詞族成員的複合詞。"),
    "guide.s3.title": ("Where the data comes from", "資料從哪裡來"),
    "guide.src.derivbase": ("a research database of German word families (University of Stuttgart).", "德文詞族研究資料庫（斯圖加特大學）。"),
    "guide.src.wiktionary": ("definitions, grammar, example sentences and word forms.", "釋義、文法資訊、例句與各種詞形。"),
    "guide.src.charsplit": ("a tool that splits compound words into their parts.", "把複合詞拆成組成部分的工具。"),
    "guide.src.wordfreq": ("how common each word is.", "每個詞有多常用。"),
    "guide.s3.body": ("All of this is combined automatically when the site is built. Nothing you type is sent to a server.", "這些資料在網站建置時自動整合。你輸入的內容不會傳送到任何伺服器。"),
    "guide.s4.title": ("How levels work", "等級怎麼來的"),
    "guide.s4.body": ("Levels (A1–C2) are estimated from how often a word appears in everyday German. They are a guide, not an official CEFR list. Separable verbs are often split in sentences, so their frequency is adjusted. Levels marked with a dashed border are estimates.", "等級（A1–C2）是依單字在日常德文中出現的頻率估計的，僅供參考，並非官方 CEFR 詞表。可分動詞在句子中常被拆開，因此其頻率經過調整。虛線外框表示估計值。"),
    "guide.s5.title": ("Good to know", "使用前須知"),
    "guide.s5.body": ("Everything here is generated automatically, so some links, splits or definitions may be wrong. A dashed underline means a word split is a guess. Some words have no Chinese definition yet; English is shown instead.", "所有內容皆為自動產生，部分連結、切分或釋義可能有誤。虛線底線表示該詞的切分是推測。部分詞尚無中文釋義，會改顯示英文。"),
    "guide.report": ("Report a problem", "回報問題"),
    "guide.s6.title": ("Licenses", "授權"),
    "guide.s6.body": ("The data is shared under CC BY-SA 4.0 and the code under the MIT License. Full credits are on GitHub.", "資料以 CC BY-SA 4.0 分享，程式碼採 MIT 授權。完整出處請見 GitHub。"),
    "guide.levelsNote": ("German has no openly licensed CEFR word list, so all levels are estimated from word frequency.", "德文沒有開放授權的 CEFR 詞表，因此所有等級皆依詞頻估計。"),
    "guide.separableNote": ("Separable verbs are often split in text, so their frequency is adjusted upward.", "可分動詞在文本中常被拆開，因此其詞頻經過向上調整。"),
    "guide.licenses": ("Data sources and licenses", "資料來源與授權"),
    "guide.legend": ("Legend", "圖例"),
}

root = pathlib.Path(__file__).resolve().parent.parent / "src" / "i18n"
root.mkdir(parents=True, exist_ok=True)
for i, name in enumerate(["en", "zh-Hant"]):
    data = {k: v[i] for k, v in S.items()}
    (root / f"{name}.json").write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", "utf-8")
print(len(S), "strings")
